# Configuration file for Telegram Reaction Bot

telegram:
  session_name: 'my_session'  # Customize your session name for the Telethon client
  api_id: ${TELEGRAM_API_ID}  # API ID, set from environment variables
  api_hash: ${TELEGRAM_API_HASH}  # API Hash, set from environment variables
  bot_token: ${TELEGRAM_BOT_TOKEN}  # Bot Token, set from environment variables
  owner_id: ${OWNER_USER_ID}  # Owner User ID, set from environment variables

logging:
  log_file: 'logs/bot.log'    # Path to the log file where logs will be stored
  level: ${LOG_LEVEL}         # Logging level, set from environment variables: DEBUG, INFO, WARNING, ERROR, CRITICAL

health_check:
  interval: 300               # Health check interval in seconds (default is 5 minutes)

notifications:
  retry_attempts: 3           # Number of retry attempts for sending messages
  retry_delay: 2              # Delay between retry attempts in seconds

advanced_settings:
  max_reactions_per_message: 100  # Limit on the number of reactions processed per message
  fetch_user_data: true       # Whether to fetch detailed user data for reactions
